#!/usr/bin/env python3
"""
fix_imports.py — [iter_234 P2] 生成"修好的 filelist" (会写文件的动作, 移出 CLI)

背景 (方豆 2026-09-09): `sv_query` 只读 —— 不改 RTL, 也不写项目文件。
CLI 的 `diagnose imports` 只报告 (哪些 undeclared identifier、定义在哪个文件);
**写新 filelist 的能力搬到本工具**, 与 `tools/fix_timescale.py` 同一模式。

复用 CLI 的分析逻辑 (不复制): `cli.core.diagnose.imports` 里的扫描/建议函数。

用法:
    # 只报告 (等价于 CLI 的 diagnose imports)
    python tools/fix_imports.py --filelist project.f

    # 生成修好的 filelist (不覆盖原文件; 目标路径必须与原 filelist 不同)
    python tools/fix_imports.py --filelist project.f --write project_fixed.f

安全约束 (实测过的 footgun):
    目标路径 == 原 filelist 时**拒绝写入** —— 早期 CLI 版本会先读原文件再原地覆盖。
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# [iter_234 P2] 统一路径引导 (无条件插到最前; 见 tools/_bootstrap.py)
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _bootstrap import ensure_src_first, REPO_ROOT  # noqa: E402

ensure_src_first()

from cli._common import collect_elaboration_diagnostics  # noqa: E402
from cli.core.diagnose.imports import (  # noqa: E402
    _build_suggestions,
    load_existing_files,
    resolve_project_root,
)


def main() -> int:
    ap = argparse.ArgumentParser(description="[iter_234 P2] 生成修好的 filelist (会写文件)")
    ap.add_argument("--filelist", required=True, help="原 filelist (.f/.fl)")
    ap.add_argument("--project-root", default=None, help="要扫描的目录 (默认 filelist 同级的 src/)")
    ap.add_argument("--write", default=None, help="把新 filelist 写到该路径 (必须 != 原 filelist)")
    ap.add_argument("--log-level", default="ERROR", help="编译器日志级别")
    ap.add_argument("--top", type=int, default=50, help="打印条数上限")
    args = ap.parse_args()

    fl_path = Path(args.filelist)
    if not fl_path.exists():
        print(f"Error: filelist not found: {fl_path}", file=sys.stderr)
        return 1

    project_root = resolve_project_root(fl_path, args.project_root)
    existing_files = load_existing_files(fl_path)
    diag = collect_elaboration_diagnostics(filelist=str(fl_path), log_level=args.log_level)
    if diag.compile_failed and not diag.errors:
        print(f"Error: {diag.failure}", file=sys.stderr)
        return 1
    errors = diag.errors
    result = _build_suggestions(errors, project_root, existing_files)

    fixable = [s for s in result["identifiers"] if s["fixable"]]
    print(f"=== fix imports (writer) ===")
    print(f"filelist: {fl_path} | project root: {project_root}")
    print(f"errors: {len(errors)} | fixable identifier(s): {len(fixable)}\n")
    for s in fixable[: args.top]:
        print(f"  🟢 {s['identifier']}  ({s['count']} 处)  定义在: {s.get('found_in')}")

    if not args.write:
        print("\n(未指定 --write, 只报告。加 --write <new.f> 才会写文件)")
        return 0

    out = Path(args.write)
    if out.resolve() == fl_path.resolve():
        # 明确拒绝, 不静默"原地重写" (早期 CLI 实现的 footgun)
        print(f"❌ 拒绝写入: --write 目标与原 filelist 相同 ({out}) — 请换一个路径", file=sys.stderr)
        return 2

    new_files: list[Path] = []
    seen: set = set()
    for s in fixable:
        fp = Path(s["found_in"])
        if fp not in seen and fp not in existing_files:
            new_files.append(fp)
            seen.add(fp)

    out.write_text(
        "# Generated by tools/fix_imports.py\n"
        f"# Project: {project_root}\n"
        f"# Added {len(new_files)} file(s) to fix {len(fixable)} identifier(s)\n\n"
        + fl_path.read_text(encoding="utf-8")
        + "\n\n# === Auto-added by fix imports ===\n"
        + "".join(f"{fp}\n" for fp in new_files),
        encoding="utf-8",
    )
    print(f"\n✅ Wrote new filelist: {out}")
    print(f"   Added {len(new_files)} file(s)")
    print(f"\nNext: python run_cli.py diagnose report --filelist {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
